# Generated by Django 5.2.7 on 2025-12-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pouch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='posted_on',
        ),
    ]
